# Generated by Django 4.2.13 on 2024-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_login_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_require',
        ),
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
