# Generated by Django 4.2.13 on 2024-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_login_require_post_login_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='statics/img/default/default_image.png', upload_to='blog/'),
        ),
    ]
